steps:
- name: 'node:8.12.0'
  entrypoint: npm
  args: ['install']
- name: 'node:8.12.0'
  entrypoint: npm
  args: ['install']
- name: 'node:8.12.0'
  entrypoint: npm
  args: ['run','lint:js']
####
# Disabled untill i figure out how to add google chrome by default to these
####
# - name: 'node:8.12.0'
#   entrypoint: npm
#   args: ['run','test']